### ISSUE TITLE
No letters in password combinations

### ISSUE THREAD

**Issue by TechGeekMic** [TechGeekMic/DotPass#2]
## How the issue is caused
https://user-images.githubusercontent.com/77752310/106393826-137a9180-63f1-11eb-973b-d5ebc10b5e0b.mp4
As you can see in the attached video, I entered option 1, which generates just numbers. This occurs for option 2 and 3, as well.

## More details
We are currently working on a fix for this and by next release, it should be fixed. If not, please provide some source code that might help us get it done quicker. Once the issue is fixed, we will close it here.

**Thank you,**
Micah/TheTechGeekMicx

**Comment by TechGeekMic** [comment]
We have worked on a fix and this should be resolved. Thank you.

**Comment by MX-Mic** [comment]
This issue was before official release, and when PasswordOffline was called "DotPass"
